server:
  port: 8085

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/pro_shop?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Yang2000620
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.56.132
    username: guest
    password: guest
    virtual-host: /shop
  redis:
    host: 192.168.56.132

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

mybatis:
  type-aliases-package: com.yzx.shop.user.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

