server:
  port: 8081

spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/pro_shop?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Yang2000620
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.56.132
    username: guest
    password: guest
    virtual-host: /shop
    template:
      exchange: shop.item.exchange
    publisher-confirms: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka
  instance:
   instance-id: ${spring.cloud.client.ip-address}:${server.port}
   prefer-ip-address: true

mybatis:
  type-aliases-package: com.yzx.shop.item.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mysql/*.xml


